using System.Data.Entity.Migrations;
using Business.DataAccess.Private.DatabaseContext;
using Business.DataAccess.Public.Entities;

namespace Project.Domain.Migrations
{

    internal sealed partial class Configuration 
    {
        private void SeedRegions(EFDBContext context)
        {
            context.Countries.AddOrUpdate(m => m.Value,
                new RegionCountry() {Id = 1, Value = "Абхазия"},
                new RegionCountry() {Id = 2, Value = "Австралия"},
                new RegionCountry() {Id = 3, Value = "Австрия"},
                new RegionCountry() {Id = 4, Value = "Азербайджан"},
                new RegionCountry() {Id = 5, Value = "Албания"},
                new RegionCountry() {Id = 6, Value = "Алжир"},
                new RegionCountry() {Id = 7, Value = "Американское Самоа"},
                new RegionCountry() {Id = 8, Value = "Ангилья"},
                new RegionCountry() {Id = 9, Value = "Ангола"},
                new RegionCountry() {Id = 10, Value = "Андорра"},
                new RegionCountry() {Id = 11, Value = "Антарктида"},
                new RegionCountry() {Id = 12, Value = "Антигуа и Барбуда"},
                new RegionCountry() {Id = 13, Value = "Аргентина"},
                new RegionCountry() {Id = 14, Value = "Армения"},
                new RegionCountry() {Id = 15, Value = "Аруба"},
                new RegionCountry() {Id = 16, Value = "Афганистан"},
                new RegionCountry() {Id = 17, Value = "Багамы"},
                new RegionCountry() {Id = 18, Value = "Бангладеш"},
                new RegionCountry() {Id = 19, Value = "Барбадос"},
                new RegionCountry() {Id = 20, Value = "Бахрейн"},
                new RegionCountry() {Id = 21, Value = "Беларусь"},
                new RegionCountry() {Id = 22, Value = "Белиз"},
                new RegionCountry() {Id = 23, Value = "Бельгия"},
                new RegionCountry() {Id = 24, Value = "Бенин"},
                new RegionCountry() {Id = 25, Value = "Бермуды"},
                new RegionCountry() {Id = 26, Value = "Болгария"},
                new RegionCountry() {Id = 27, Value = "Боливия, Многонациональное Государство"},
                new RegionCountry() {Id = 28, Value = "Бонайре, Саба и Синт-Эстатиус"},
                new RegionCountry() {Id = 29, Value = "Босния и Герцеговина"},
                new RegionCountry() {Id = 30, Value = "Ботсвана"},
                new RegionCountry() {Id = 31, Value = "Бразилия"},
                new RegionCountry() {Id = 32, Value = "Британская территория в Индийском океане"},
                new RegionCountry() {Id = 33, Value = "Бруней-Даруссалам"},
                new RegionCountry() {Id = 34, Value = "Буркина-Фасо"},
                new RegionCountry() {Id = 35, Value = "Бурунди"},
                new RegionCountry() {Id = 36, Value = "Бутан"},
                new RegionCountry() {Id = 37, Value = "Вануату"},
                new RegionCountry() {Id = 38, Value = "Венгрия"},
                new RegionCountry() {Id = 39, Value = "Венесуэла Боливарианская Республика"},
                new RegionCountry() {Id = 40, Value = "Виргинские острова, Британские"},
                new RegionCountry() {Id = 41, Value = "Виргинские острова, США"},
                new RegionCountry() {Id = 42, Value = "Вьетнам"},
                new RegionCountry() {Id = 43, Value = "Габон"},
                new RegionCountry() {Id = 44, Value = "Гаити"},
                new RegionCountry() {Id = 45, Value = "Гайана"},
                new RegionCountry() {Id = 46, Value = "Гамбия"},
                new RegionCountry() {Id = 47, Value = "Гана"},
                new RegionCountry() {Id = 48, Value = "Гваделупа"},
                new RegionCountry() {Id = 49, Value = "Гватемала"},
                new RegionCountry() {Id = 50, Value = "Гвинея"},
                new RegionCountry() {Id = 51, Value = "Гвинея-Бисау"},
                new RegionCountry() {Id = 52, Value = "Германия"},
                new RegionCountry() {Id = 53, Value = "Гернси"},
                new RegionCountry() {Id = 54, Value = "Гибралтар"},
                new RegionCountry() {Id = 55, Value = "Гондурас"},
                new RegionCountry() {Id = 56, Value = "Гонконг"},
                new RegionCountry() {Id = 57, Value = "Гренада"},
                new RegionCountry() {Id = 58, Value = "Гренландия"},
                new RegionCountry() {Id = 59, Value = "Греция"},
                new RegionCountry() {Id = 60, Value = "Грузия"},
                new RegionCountry() {Id = 61, Value = "Гуам"},
                new RegionCountry() {Id = 62, Value = "Дания"},
                new RegionCountry() {Id = 63, Value = "Джерси"},
                new RegionCountry() {Id = 64, Value = "Джибути"},
                new RegionCountry() {Id = 65, Value = "Доминика"},
                new RegionCountry() {Id = 66, Value = "Доминиканская Республика"},
                new RegionCountry() {Id = 67, Value = "Египет"},
                new RegionCountry() {Id = 68, Value = "Замбия"},
                new RegionCountry() {Id = 69, Value = "Западная Сахара"},
                new RegionCountry() {Id = 70, Value = "Зимбабве"},
                new RegionCountry() {Id = 71, Value = "Израиль"},
                new RegionCountry() {Id = 72, Value = "Индия"},
                new RegionCountry() {Id = 73, Value = "Индонезия"},
                new RegionCountry() {Id = 74, Value = "Иордания"},
                new RegionCountry() {Id = 75, Value = "Ирак"},
                new RegionCountry() {Id = 76, Value = "Иран, Исламская Республика"},
                new RegionCountry() {Id = 77, Value = "Ирландия"},
                new RegionCountry() {Id = 78, Value = "Исландия"},
                new RegionCountry() {Id = 79, Value = "Испания"},
                new RegionCountry() {Id = 80, Value = "Италия"},
                new RegionCountry() {Id = 81, Value = "Йемен"},
                new RegionCountry() {Id = 82, Value = "Кабо-Верде"},
                new RegionCountry() {Id = 83, Value = "Казахстан"},
                new RegionCountry() {Id = 84, Value = "Камбоджа"},
                new RegionCountry() {Id = 85, Value = "Камерун"},
                new RegionCountry() {Id = 86, Value = "Канада"},
                new RegionCountry() {Id = 87, Value = "Катар"},
                new RegionCountry() {Id = 88, Value = "Кения"},
                new RegionCountry() {Id = 89, Value = "Кипр"},
                new RegionCountry() {Id = 90, Value = "Киргизия"},
                new RegionCountry() {Id = 91, Value = "Кирибати"},
                new RegionCountry() {Id = 92, Value = "Китай"},
                new RegionCountry() {Id = 93, Value = "Кокосовые (Килинг) острова"},
                new RegionCountry() {Id = 94, Value = "Колумбия"},
                new RegionCountry() {Id = 95, Value = "Коморы"},
                new RegionCountry() {Id = 96, Value = "Конго"},
                new RegionCountry() {Id = 97, Value = "Конго, Демократическая Республика"},
                new RegionCountry() {Id = 98, Value = "Корея, Народно-Демократическая Республика"},
                new RegionCountry() {Id = 99, Value = "Корея, Республика"},
                new RegionCountry() {Id = 100, Value = "Коста-Рика"},
                new RegionCountry() {Id = 101, Value = "Кот д'Ивуар"},
                new RegionCountry() {Id = 102, Value = "Куба"},
                new RegionCountry() {Id = 103, Value = "Кувейт"},
                new RegionCountry() {Id = 104, Value = "Кюрасао"},
                new RegionCountry() {Id = 105, Value = "Лаос"},
                new RegionCountry() {Id = 106, Value = "Латвия"},
                new RegionCountry() {Id = 107, Value = "Лесото"},
                new RegionCountry() {Id = 108, Value = "Ливан"},
                new RegionCountry() {Id = 109, Value = "Ливийская Арабская Джамахирия"},
                new RegionCountry() {Id = 110, Value = "Либерия"},
                new RegionCountry() {Id = 111, Value = "Лихтенштейн"},
                new RegionCountry() {Id = 112, Value = "Литва"},
                new RegionCountry() {Id = 113, Value = "Люксембург"},
                new RegionCountry() {Id = 114, Value = "Маврикий"},
                new RegionCountry() {Id = 115, Value = "Мавритания"},
                new RegionCountry() {Id = 116, Value = "Мадагаскар"},
                new RegionCountry() {Id = 117, Value = "Майотта"},
                new RegionCountry() {Id = 118, Value = "Макао"},
                new RegionCountry() {Id = 119, Value = "Малави"},
                new RegionCountry() {Id = 120, Value = "Малайзия"},
                new RegionCountry() {Id = 121, Value = "Мали"},
                new RegionCountry() {Id = 122, Value = "Малые Тихоокеанские отдаленные острова Соединенных Штатов"},
                new RegionCountry() {Id = 123, Value = "Мальдивы"},
                new RegionCountry() {Id = 124, Value = "Мальта"},
                new RegionCountry() {Id = 125, Value = "Марокко"},
                new RegionCountry() {Id = 126, Value = "Мартиника"},
                new RegionCountry() {Id = 127, Value = "Маршалловы острова"},
                new RegionCountry() {Id = 128, Value = "Мексика"},
                new RegionCountry() {Id = 129, Value = "Микронезия, Федеративные Штаты"},
                new RegionCountry() {Id = 130, Value = "Мозамбик"},
                new RegionCountry() {Id = 131, Value = "Молдова, Республика"},
                new RegionCountry() {Id = 132, Value = "Монако"},
                new RegionCountry() {Id = 133, Value = "Монголия"},
                new RegionCountry() {Id = 134, Value = "Монтсеррат"},
                new RegionCountry() {Id = 135, Value = "Мьянма"},
                new RegionCountry() {Id = 136, Value = "Намибия"},
                new RegionCountry() {Id = 137, Value = "Науру"},
                new RegionCountry() {Id = 138, Value = "Непал"},
                new RegionCountry() {Id = 139, Value = "Нигер"},
                new RegionCountry() {Id = 140, Value = "Нигерия"},
                new RegionCountry() {Id = 141, Value = "Нидерланды"},
                new RegionCountry() {Id = 142, Value = "Никарагуа"},
                new RegionCountry() {Id = 143, Value = "Ниуэ"},
                new RegionCountry() {Id = 144, Value = "Новая Зеландия"},
                new RegionCountry() {Id = 145, Value = "Новая Каледония"},
                new RegionCountry() {Id = 146, Value = "Норвегия"},
                new RegionCountry() {Id = 147, Value = "Объединенные Арабские Эмираты"},
                new RegionCountry() {Id = 148, Value = "Оман"},
                new RegionCountry() {Id = 149, Value = "Остров Буве"},
                new RegionCountry() {Id = 150, Value = "Остров Мэн"},
                new RegionCountry() {Id = 151, Value = "Остров Норфолк"},
                new RegionCountry() {Id = 152, Value = "Остров Рождества"},
                new RegionCountry() {Id = 153, Value = "Остров Херд и острова Макдональд"},
                new RegionCountry() {Id = 154, Value = "Острова Кайман"},
                new RegionCountry() {Id = 155, Value = "Острова Кука"},
                new RegionCountry() {Id = 156, Value = "Острова Теркс и Кайкос"},
                new RegionCountry() {Id = 157, Value = "Пакистан"},
                new RegionCountry() {Id = 158, Value = "Палау"},
                new RegionCountry() {Id = 159, Value = "Палестинская территория, оккупированная"},
                new RegionCountry() {Id = 160, Value = "Панама"},
                new RegionCountry() {Id = 161, Value = "Папский Престол (Государство — город Ватикан)"},
                new RegionCountry() {Id = 162, Value = "Папуа-Новая Гвинея"},
                new RegionCountry() {Id = 163, Value = "Парагвай"},
                new RegionCountry() {Id = 164, Value = "Перу"},
                new RegionCountry() {Id = 165, Value = "Питкерн"},
                new RegionCountry() {Id = 166, Value = "Польша"},
                new RegionCountry() {Id = 167, Value = "Португалия"},
                new RegionCountry() {Id = 168, Value = "Пуэрто-Рико"},
                new RegionCountry() {Id = 169, Value = "Республика Македония"},
                new RegionCountry() {Id = 170, Value = "Реюньон"},
                new RegionCountry() {Id = 171, Value = "Россия", Sort = 1},
                new RegionCountry() {Id = 172, Value = "Руанда"},
                new RegionCountry() {Id = 173, Value = "Румыния"},
                new RegionCountry() {Id = 174, Value = "Самоа"},
                new RegionCountry() {Id = 175, Value = "Сан-Марино"},
                new RegionCountry() {Id = 176, Value = "Сан-Томе и Принсипи"},
                new RegionCountry() {Id = 177, Value = "Саудовская Аравия"},
                new RegionCountry() {Id = 178, Value = "Свазиленд"},
                new RegionCountry() {Id = 179, Value = "Святая Елена, Остров вознесения, Тристан-да-Кунья"},
                new RegionCountry() {Id = 180, Value = "Северные Марианские острова"},
                new RegionCountry() {Id = 181, Value = "Сен-Бартельми"},
                new RegionCountry() {Id = 182, Value = "Сен-Мартен"},
                new RegionCountry() {Id = 183, Value = "Сенегал"},
                new RegionCountry() {Id = 184, Value = "Сент-Винсент и Гренадины"},
                new RegionCountry() {Id = 185, Value = "Сент-Люсия"},
                new RegionCountry() {Id = 186, Value = "Сент-Китс и Невис"},
                new RegionCountry() {Id = 187, Value = "Сент-Пьер и Микелон"},
                new RegionCountry() {Id = 188, Value = "Сербия"},
                new RegionCountry() {Id = 189, Value = "Сейшелы"},
                new RegionCountry() {Id = 190, Value = "Сингапур"},
                new RegionCountry() {Id = 191, Value = "Синт-Мартен"},
                new RegionCountry() {Id = 192, Value = "Сирийская Арабская Республика"},
                new RegionCountry() {Id = 193, Value = "Словакия"},
                new RegionCountry() {Id = 194, Value = "Словения"},
                new RegionCountry() {Id = 195, Value = "Соединенное Королевство"},
                new RegionCountry() {Id = 196, Value = "Соединенные Штаты"},
                new RegionCountry() {Id = 197, Value = "Соломоновы острова"},
                new RegionCountry() {Id = 198, Value = "Сомали"},
                new RegionCountry() {Id = 199, Value = "Судан"},
                new RegionCountry() {Id = 200, Value = "Суринам"},
                new RegionCountry() {Id = 201, Value = "Сьерра-Леоне"},
                new RegionCountry() {Id = 202, Value = "Таджикистан"},
                new RegionCountry() {Id = 203, Value = "Таиланд"},
                new RegionCountry() {Id = 204, Value = "Тайвань (Китай)"},
                new RegionCountry() {Id = 205, Value = "Танзания, Объединенная Республика"},
                new RegionCountry() {Id = 206, Value = "Тимор-Лесте"},
                new RegionCountry() {Id = 207, Value = "Того"},
                new RegionCountry() {Id = 208, Value = "Токелау"},
                new RegionCountry() {Id = 209, Value = "Тонга"},
                new RegionCountry() {Id = 210, Value = "Тринидад и Тобаго"},
                new RegionCountry() {Id = 211, Value = "Тувалу"},
                new RegionCountry() {Id = 212, Value = "Тунис"},
                new RegionCountry() {Id = 213, Value = "Туркмения"},
                new RegionCountry() {Id = 214, Value = "Турция"},
                new RegionCountry() {Id = 215, Value = "Уганда"},
                new RegionCountry() {Id = 216, Value = "Узбекистан"},
                new RegionCountry() {Id = 217, Value = "Украина"},
                new RegionCountry() {Id = 218, Value = "Уоллис и Футуна"},
                new RegionCountry() {Id = 219, Value = "Уругвай"},
                new RegionCountry() {Id = 220, Value = "Фарерские острова"},
                new RegionCountry() {Id = 221, Value = "Фиджи"},
                new RegionCountry() {Id = 222, Value = "Филиппины"},
                new RegionCountry() {Id = 223, Value = "Финляндия"},
                new RegionCountry() {Id = 224, Value = "Фолклендские острова (Мальвинские)"},
                new RegionCountry() {Id = 225, Value = "Франция"},
                new RegionCountry() {Id = 226, Value = "Французская Гвиана"},
                new RegionCountry() {Id = 227, Value = "Французская Полинезия"},
                new RegionCountry() {Id = 228, Value = "Французские Южные территории"},
                new RegionCountry() {Id = 229, Value = "Хорватия"},
                new RegionCountry() {Id = 230, Value = "Центрально-Африканская Республика"},
                new RegionCountry() {Id = 231, Value = "Чад"},
                new RegionCountry() {Id = 232, Value = "Черногория"},
                new RegionCountry() {Id = 233, Value = "Чешская Республика"},
                new RegionCountry() {Id = 234, Value = "Чили"},
                new RegionCountry() {Id = 235, Value = "Швейцария"},
                new RegionCountry() {Id = 236, Value = "Швеция"},
                new RegionCountry() {Id = 237, Value = "Шпицберген и Ян Майен"},
                new RegionCountry() {Id = 238, Value = "Шри-Ланка"},
                new RegionCountry() {Id = 239, Value = "Эквадор"},
                new RegionCountry() {Id = 240, Value = "Экваториальная Гвинея"},
                new RegionCountry() {Id = 241, Value = "Эландские острова"},
                new RegionCountry() {Id = 242, Value = "Эль-Сальвадор"},
                new RegionCountry() {Id = 243, Value = "Эритрея"},
                new RegionCountry() {Id = 244, Value = "Эстония"},
                new RegionCountry() {Id = 245, Value = "Эфиопия"},
                new RegionCountry() {Id = 246, Value = "Южная Африка"},
                new RegionCountry() {Id = 247, Value = "Южная Джорджия и Южные Сандвичевы острова"},
                new RegionCountry() {Id = 248, Value = "Южная Осетия"},
                new RegionCountry() {Id = 249, Value = "Южный Судан"},
                new RegionCountry() {Id = 250, Value = "Ямайка"},
                new RegionCountry() {Id = 251, Value = "Япония"}

                );
        }
    }
}
